from __future__ import annotations
from typing import Protocol, List, Optional
from ..models import Project, ProjectCreate, ProjectUpdate, Profile, ProfileUpdate, Skill, Asset, AssetCreate


class Repository(Protocol):
    """Protocol for repository operations used by services."""

    # Projects
    def list_projects(self) -> List[Project]: ...
    def get_project(self, project_id: str) -> Optional[Project]: ...
    def create_project(self, data: ProjectCreate) -> Project: ...
    def update_project(self, project_id: str, data: ProjectUpdate) -> Optional[Project]: ...
    def delete_project(self, project_id: str) -> bool: ...

    # Profile
    def get_profile(self) -> Profile: ...
    def update_profile(self, data: ProfileUpdate) -> Profile: ...

    # Skills
    def list_skills(self) -> List[Skill]: ...
    def add_skill(self, skill: Skill) -> Skill: ...
    def delete_skill(self, name: str) -> bool: ...

    # Assets
    def list_assets(self) -> List[Asset]: ...
    def get_asset(self, asset_id: str) -> Optional[Asset]: ...
    def create_asset(self, data: AssetCreate, *, filename: str | None, content_type: str | None, size_bytes: int | None) -> Asset: ...
